const action = {
  SIGN_UP_REQUEST: 'auth/SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'auth/SIGN_UP_SUCCESS',
  SIGN_IN_REQUEST: 'auth/SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'auth/SIGN_IN_SUCCESS',
  SIGN_OUT_REQUEST: 'auth/SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS: 'auth/SIGN_OUT_SUCCESS',
  REFRESH_CURRENT_USER_START: 'auth/REFRESH_CURRENT_USER_START',
  REFRESH_CURRENT_USER_SUCCESS: 'auth/REFRESH_CURRENT_USER_SUCCESS',
  ERROR: 'auth/SIGN_UP_ERROR',
};

export default action;
